### ISSUE TITLE
[cow.js]103行目でUncaught TypeErrorが出てプログラムが正常に動かない。

### ISSUE THREAD

**Issue by Neko288** [crudslag/COW#5]
## 問題
cow.jsの103行目「.getElementsByTagName("li");」において「Uncaught TypeError: Cannot read properties of undefined (reading 'getElementsByTagName') 」というエラーが起きて、プログラムが正常に動かない。(動画を視聴済みでも、次の動画に自動で行かない)

この問題を解決してもらえると大変助かります。

## エラーログ
![image](https://github.com/crudslag/COW/assets/79035426/3779cd4b-e16a-4b0b-bc46-d42e18097337)

## 期待する動作
N予備校の動画を一本最後まで見終わったら、自動的に次の動画を再生するようにする。

## 問題が起こった実行環境
-Windows 11 Home
-Microsoft edge バージョン 118.0.2088.46 (公式ビルド) (64 ビット)
-Chrome バージョン: 118.0.5993.89（Official Build） （64 ビット）
Edge、Chrome双方で同じ問題が発生する。

## エラーの発生状況
N予備校の動画を再生して、関数next()が呼び出されたタイミングで起きる。

いつもこの拡張機能のおかげで助かっています。開発ありがとうございます。

**Comment by crudslag** [comment]
ok

**Comment by crudslag** [comment]
4c78d51
fixed

**Comment by Neko288** [comment]
Many thanks!!!!
